/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Untitled.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Untitled.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1084828503.geometry} material={materials.mat21} position={[-0.001, 3.154, 0]}>
        <mesh geometry={nodes.group1027479694.geometry} material={materials.mat21} />
        <mesh geometry={nodes.group1081505243.geometry} material={materials.mat21} />
        <mesh geometry={nodes.group895107068.geometry} material={materials.mat21} position={[0.005, 0.728, -0.174]} rotation={[0, 0, -2.108]}>
          <mesh geometry={nodes.group1638284413.geometry} material={materials.mat21} position={[-0.001, 0.002, 0.049]} />
          <mesh geometry={nodes.group2091045647.geometry} material={materials.mat21} position={[-0.001, 0.002, 0.049]} rotation={[0, 0, -2.143]} />
          <mesh geometry={nodes.group319097306.geometry} material={materials.mat21} position={[-0.001, 0.002, 0.049]} rotation={[0, -0.026, 2.118]} />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/Untitled.glb')
