/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 WindTest1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/WindTest1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Turbine.geometry} material={nodes.Turbine.material} position={[0.023, 20.136, -0.264]} scale={[0.619, 0.619, 1.029]}>
        <mesh geometry={nodes.Rotor.geometry} material={nodes.Rotor.material} position={[0, 0.067, 1.395]} scale={[1.616, 1.616, 0.972]}>
          <mesh geometry={nodes.Blade_1.geometry} material={nodes.Blade_1.material} position={[4.878, -2.849, 0.023]} rotation={[0, 0, -2.095]} scale={[1, 1, 0.972]} />
          <mesh geometry={nodes.Blade_2.geometry} material={nodes.Blade_2.material} position={[-4.903, -2.805, 0.023]} rotation={[0, 0, 2.095]} scale={[1, 1, 0.972]} />
          <mesh geometry={nodes.Blade_3.geometry} material={nodes.Blade_3.material} position={[0.026, 5.649, 0.023]} scale={[1, 1, 0.972]} />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/WindTest1.glb')
