/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Wind.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Wind.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Turbine.geometry} material={nodes.Turbine.material} position={[0.023, 20.136, -0.264]} scale={[0.619, 0.619, 1.029]}>
        <mesh geometry={nodes.Rotor.geometry} material={nodes.Rotor.material} position={[0, 0.067, 1.395]} scale={[1.616, 1.616, 0.972]}>
          <mesh geometry={nodes.Blade_1.geometry} material={nodes.Blade_1.material} position={[0.02, -0.01, -0.001]} rotation={[0, 0, -2.097]} scale={[1, 1, 0.972]} />
          <mesh geometry={nodes.Blade_2.geometry} material={nodes.Blade_2.material} position={[-0.009, -0.014, 0.002]} rotation={[0, 0, 2.093]} scale={[1, 1, 0.972]} />
          <mesh geometry={nodes.Blade_3.geometry} material={nodes.Blade_3.material} position={[-0.004, -0.013, 0.005]} scale={[1, 1, 0.972]} />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/Wind.glb')
