/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Untitled.glb 
*/

import { React, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const Model = (props) => {
  const { nodes, materials } = useGLTF('/WindmillModel.glb')
  const rotorRef = useRef()
  const pitchRef = useRef()
  useFrame((state, delta) => {
    if (rotorRef.current) {
      rotorRef.current.rotation.z += delta * 2 // Adjust speed as needed
    }
  })

  useFrame((state, delta) => {
    if (pitchRef.current) {
      pitchRef.current.rotation.x = delta * 90 // Adjust speed as needed
    }
  })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Turbine.geometry} material={nodes.Turbine.material} position={[0.023, 20.136, -0.264]} scale={[0.619, 0.619, 1.029]}>
        <mesh ref={rotorRef} geometry={nodes.Rotor.geometry} material={nodes.Rotor.material} position={[0, 0.067, 1.395]} scale={[1.616, 1.616, 0.972]}>
          <mesh geometry={nodes.Blade_1.geometry} material={nodes.Blade_1.material} position={[0.02, -0.01, -0.001]} scale={[1, 1, 0.972]} />
          <mesh  geometry={nodes.Blade_2.geometry} material={nodes.Blade_2.material} position={[-0.009, -0.014, 0.002]} scale={[1, 1, 0.972]} />
          <mesh  geometry={nodes.Blade_3.geometry} material={nodes.Blade_3.material} position={[-0.004, -0.013, 0.005]} scale={[1, 1, 0.972]} />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/Untitled.glb')

export default Model;